services:
  server:
    build:
      context: ./server
    container_name: onepercent_taptap_generator_server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./server/data:/app/data
    ports:
      - "3000:3000"

  web:
    build:
      context: ./web
    container_name: onepercent_taptap_generator_web
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "8080:80"
